### ISSUE TITLE
README.md - not consistent and hence confusing

### ISSUE THREAD

**Issue by ak2766** [Unicon/shibboleth-idp-dockerized#28]
When building the IdP configuration, the configuration details are saved into:
`customized-shibboleth-idp/`

Later, when building the `Dockerfile`, it has:
`ADD shibboleth-idp/ /opt/shibboleth-idp/`

~~Shouldn't that~~ It ought to be:
`ADD customized-shibboleth-idp/ /opt/shibboleth-idp/`

~~Did I miss something?~~

Edit: I did try it as stated in the `README.md` and got this error:

```
Step 3 : ADD shibboleth-idp/ /opt/shibboleth-idp/
lstat shibboleth-idp/: no such file or directory
```

**Comment by jtgasper3** [comment]
Yep, all of that is correct. It's intended to be copied from where the config is dumped to your our image. The latter part of the document is an example not necessarily tied to the config files that are dumped by the config creation process. It was (or should not have) never implied that the two are connected otherwise, the config creation might as well create the Dockerfile for you too. :)

**Comment by ak2766** [comment]
Now that I've read it again with your comments in mind, it is akin to `/path/to/yadi/yada/foo.conf` I see in other instructions where the final resting place of `foo.conf` is unknown at that point in time.

Got it.

**Comment by jtgasper3** [comment]
Excellent. Closing.
