### ISSUE TITLE
Anyone tried Single Logout?

### ISSUE THREAD

**Issue by newswangerd** [Unicon/shibboleth-idp-dockerized#29]
I'm working on converting our existing IdP over to a containerized deployment.

I can't get single logout to work. When I go to log out normally the IdP presents me with a list of services that I've accessed and then logs me out of each. The containerized version of the IdP simply tells me I'm logged out without showing the services or actually logging me out of them. I'm using the same configuration that we are using on our production instance of the IdP, which does currently support SLO, so it should theoretically work.

I'm starting to wonder if this is an issue with the base image and I am curious wondering if anyone else has got this working. 

Also, where would i go to find information about SLO in the logs? I don't see any errors that might relate to this in any of the files in /opt/shibboleth-idp/logs.

Thanks!

**Comment by jtgasper3** [comment]
I've not tried SLO with this base image, but I have with one that is nearly identical but running Tomcat instead of Jetty. I don't think that would make a difference. 

I'd double check your settings (https://wiki.shibboleth.net/confluence/display/IDP30/LogoutConfiguration). Something in the IdP's webflow is not triggering the proper branch to execute.

**Comment by newswangerd** [comment]
I found the issue. My service provider was misconfigured. SLO on the image looks like it works fine!

**Comment by jtgasper3** [comment]
Excellent. Thanks for following up.
